### PR TITLE
Release 22.06

### PR DESCRIPTION
**Pull request by tchx84**

### CODE REVIEW

**Comment by tchx84** [comment]
@barthalion @bilelmoussaoui can someone remind me how I add this new 22.06 branch for this BaseApp ? :sweat_smile:

**Comment by hfiguiere** [comment]
`git push -u origin v22.06:branch/22.06` (command may need to be adjusted)

It is the `branch/*` branch name that is important

**Comment by tchx84** [comment]
> `git push -u origin v22.06:branch/22.06` (command may need to be adjusted)
> 
> It is the `branch/*` branch name that is important

Thanks, that was the part I wasn't sure of :+1:

**Comment by tchx84** [comment]
Maybe one of the admins can set branch/22.06 as the default branch? It won't let me.

**Comment by hfiguiere** [comment]
@barthalion @bilelmoussaoui @nedrichards can (I can't)

**Comment by barthalion** [comment]
Done.

**Pull request closed without merging**
